### PR TITLE
fix processing of multipacket messages

### PR DESCRIPTION
**Pull request by stuqdog**
Fixes a bug in the rust-sdk whereby messages too long to send in a single packet would have bytes carved out of them.

### CODE REVIEW

**Review by maximpertsov — COMMENTED** [review]
looks correct, but might be worth adding a unit test to validate this logic and capture a few examples

**Review by npmenard — APPROVED** [review]
LGTM

**Comment by stuqdog** [comment]
> looks correct, but might be worth adding a unit test to validate this logic and capture a few examples

per offline discussion, moving this to a separate ticket [here](https://viam.atlassian.net/browse/RSDK-769)

**Review by cheukt — APPROVED** [review]

**Review by njooma — APPROVED** [review]
`it_was_all_a_stream` is a great variable name

**Pull request merged**
